---
title: 1.什么是操作系统
date: 2021/10/14 23:30:00
categories:
- 操作系统
tags:
- 操作系统
---

# 1.什么是操作系统

什么是操作系统

- 是计算器硬件和应用之间的一层软件
  - 方便我们使用硬件，如使用显存
  - 高效使用硬件，如开多个终端（窗口）

- 管理了那些硬件

  - | **CPU管理**  | **内存管理** | **终端管理** | **磁盘管理** |
    | ------------ | ------------ | ------------ | ------------ |
    | **文件管理** | 网络管理     | 电源管理     | 多核管理     |







